# Generated by Django 4.1.5 on 2023-02-21 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün Adı')),
                ('text', models.TextField(max_length=500, verbose_name='Açıklama')),
                ('image', models.FileField(upload_to='', verbose_name='Fotoğraf')),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('stok', models.IntegerField(default=0, verbose_name='Stok')),
                ('date_now', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('likes', models.FloatField(default=0, verbose_name='Beğeni Ortalaması')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı (Satıcı)')),
            ],
        ),
    ]
