# Generated by Django 4.1.5 on 2023-03-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments_number',
            field=models.IntegerField(default=0, verbose_name='Yorum Sayısı'),
        ),
    ]
